#!/bin/bash
# Run ScopeMedicalExpert on the first 175 MedQA test examples using GPUs 0 and 1.
# Candidate generation matches original SCOPE diverse beam settings; final answer stays mediQ/HF greedy.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
export MAX_EXAMPLES="${MAX_EXAMPLES:-175}"
export TAG="${TAG:-medical_scope_qwen3_4b_scope_decode_top175}"

export SCOPE_MEDICAL_NUM_CANDIDATES="${SCOPE_MEDICAL_NUM_CANDIDATES:-5}"
export SCOPE_MEDICAL_CANDIDATE_MAX_NEW_TOKENS="${SCOPE_MEDICAL_CANDIDATE_MAX_NEW_TOKENS:-500}"
export SCOPE_MEDICAL_CANDIDATE_NUM_BEAM_GROUPS="${SCOPE_MEDICAL_CANDIDATE_NUM_BEAM_GROUPS:-5}"
export SCOPE_MEDICAL_CANDIDATE_DIVERSITY_PENALTY="${SCOPE_MEDICAL_CANDIDATE_DIVERSITY_PENALTY:-1.0}"
export SCOPE_MEDICAL_CANDIDATE_REPETITION_PENALTY="${SCOPE_MEDICAL_CANDIDATE_REPETITION_PENALTY:-1.0}"

export SCOPE_MEDICAL_EMBED_DEVICE="${SCOPE_MEDICAL_EMBED_DEVICE:-cuda:1}"
export SCOPE_MEDICAL_TRANSITION_DEVICE="${SCOPE_MEDICAL_TRANSITION_DEVICE:-cuda:1}"
export SCOPE_MEDICAL_REWARD_DEVICE="${SCOPE_MEDICAL_REWARD_DEVICE:-cuda:1}"

exec "$SCRIPT_DIR/run_scope_medical.sh"
